# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Pods for FlatironLibrary
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'FlatironLibrary' do
    pod 'Alamofire', '~> 4.4'
end